import type { HearingSheet } from "@/types/hearing";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function nl2br(s: string): string {
  return esc(s).replace(/\n/g, "<br>");
}

function section(title: string, rows: [string, string][]): string {
  const filtered = rows.filter(([, v]) => v.trim());
  if (filtered.length === 0) return "";
  return `
    <div class="section">
      <h2>${esc(title)}</h2>
      <table>
        ${filtered.map(([k, v]) => `<tr><th>${esc(k)}</th><td>${nl2br(v)}</td></tr>`).join("")}
      </table>
    </div>`;
}

export function generateHearingHtml(data: HearingSheet): string {
  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ヒアリングシート - ${esc(data.clientName || "未設定")}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Hiragino Sans", sans-serif; background: #fff; color: #1e293b; padding: 40px 20px; line-height: 1.7; }
  .container { max-width: 800px; margin: 0 auto; }
  h1 { font-size: 22px; border-bottom: 3px solid #3b82f6; padding-bottom: 8px; margin-bottom: 8px; }
  .meta { font-size: 12px; color: #64748b; margin-bottom: 32px; }
  .section { margin-bottom: 28px; break-inside: avoid; }
  .section h2 { font-size: 15px; background: #f1f5f9; padding: 8px 12px; border-left: 4px solid #3b82f6; margin-bottom: 0; }
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; text-align: left; font-size: 13px; vertical-align: top; }
  th { width: 160px; background: #f8fafc; font-weight: 600; color: #475569; white-space: nowrap; }
  td { color: #1e293b; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { padding: 20px; } .section { break-inside: avoid; } }
</style>
</head>
<body>
<div class="container">
  <h1>ヒアリングシート</h1>
  <div class="meta">
    クライアント: ${esc(data.clientName || "未設定")} ／ 作成日: ${esc(data.createdAt)} ／ ステータス: ${data.status === "completed" ? "完了" : "下書き"}
  </div>

  ${section("クライアント基本情報", [
    ["会社名・団体名", data.clientName],
    ["業種", data.clientIndustry],
    ["現在のサイトURL", data.clientUrl],
    ["担当者名", data.contactPerson],
    ["メールアドレス", data.contactEmail],
    ["電話番号", data.contactPhone],
  ])}

  ${section("現状分析", [
    ["現状の課題・背景", data.currentSituation],
    ["競合サイト", data.competitors],
    ["既存資料", data.existingMaterials],
    ["アクセス状況", data.accessAnalysis],
  ])}

  ${section("SWOT分析", [
    ["強み (Strengths)", data.strengths],
    ["弱み (Weaknesses)", data.weaknesses],
    ["機会 (Opportunities)", data.opportunities],
    ["脅威 (Threats)", data.threats],
  ])}

  ${section("ターゲット・ペルソナ", [
    ["ターゲットユーザー", data.targetUsers],
    ["年齢層", data.personaAge],
    ["性別", data.personaGender],
    ["職業", data.personaOccupation],
    ["ニーズ・課題", data.personaNeeds],
    ["カスタマージャーニー", data.customerJourney],
  ])}

  ${section("戦略・ブランディング", [
    ["ブランドメッセージ", data.brandMessage],
    ["KGI（最終目標）", data.kgi],
    ["KPI（中間指標）", data.kpi],
    ["収益化方針", data.monetization],
  ])}

  ${section("要件定義", [
    ["プロジェクトの目的", data.projectGoal],
    ["サイト種別", data.siteType],
    ["必要なページ", data.requiredPages],
    ["必要な機能", data.features.join("、")],
    ["CMS", data.cmsType],
    ["SNS連携", data.snsIntegration.join("、")],
    ["レスポンシブ対応", data.responsiveRequired ? "必要" : "不要"],
    ["SEO対策", data.seoRequired ? "必要" : "不要"],
    ["アクセス解析", data.analyticsRequired ? "必要" : "不要"],
  ])}

  ${section("デザイン", [
    ["デザインの方向性", data.designPreference],
    ["参考サイトURL", data.referenceUrls],
  ])}

  ${section("予算・スケジュール", [
    ["予算", data.budgetRange],
    ["希望公開日", data.desiredLaunch],
    ["優先事項", data.priority],
  ])}

  ${section("素材・運用", [
    ["提供素材", data.materialsProvided.join("、")],
    ["ライティング担当", data.writingBy],
    ["運用体制", data.operationPlan],
    ["保守契約", data.maintenanceRequired ? "希望あり" : "希望なし"],
  ])}

  ${section("サーバー・ドメイン", [
    ["サーバー種別", data.serverType],
    ["サーバー名・プラン", data.serverName],
    ["サーバーログイン情報", data.serverLoginInfo],
    ["ドメイン名", data.domainName],
    ["ドメイン管理会社", data.domainRegistrar],
    ["ドメイン有効期限", data.domainExpiry],
    ["SSL証明書", data.sslType],
    ["メールサーバー", data.mailServer],
    ["DNS管理", data.dnsManagement],
  ])}

  ${data.notes ? section("備考", [["メモ", data.notes]]) : ""}

  <div class="footer">Generated by WebCraft</div>
</div>
</body>
</html>`;
}

export function generateHearingCsv(data: HearingSheet): string {
  const rows: [string, string][] = [
    ["会社名・団体名", data.clientName],
    ["業種", data.clientIndustry],
    ["現在のサイトURL", data.clientUrl],
    ["担当者名", data.contactPerson],
    ["メールアドレス", data.contactEmail],
    ["電話番号", data.contactPhone],
    ["現状の課題・背景", data.currentSituation],
    ["競合サイト", data.competitors],
    ["既存資料", data.existingMaterials],
    ["アクセス状況", data.accessAnalysis],
    ["強み", data.strengths],
    ["弱み", data.weaknesses],
    ["機会", data.opportunities],
    ["脅威", data.threats],
    ["ターゲットユーザー", data.targetUsers],
    ["ペルソナ年齢層", data.personaAge],
    ["ペルソナ性別", data.personaGender],
    ["ペルソナ職業", data.personaOccupation],
    ["ペルソナのニーズ", data.personaNeeds],
    ["カスタマージャーニー", data.customerJourney],
    ["ブランドメッセージ", data.brandMessage],
    ["KGI", data.kgi],
    ["KPI", data.kpi],
    ["収益化方針", data.monetization],
    ["プロジェクトの目的", data.projectGoal],
    ["サイト種別", data.siteType],
    ["必要なページ", data.requiredPages],
    ["必要な機能", data.features.join("、")],
    ["CMS", data.cmsType],
    ["デザインの方向性", data.designPreference],
    ["参考サイトURL", data.referenceUrls],
    ["レスポンシブ対応", data.responsiveRequired ? "必要" : "不要"],
    ["SEO対策", data.seoRequired ? "必要" : "不要"],
    ["アクセス解析", data.analyticsRequired ? "必要" : "不要"],
    ["SNS連携", data.snsIntegration.join("、")],
    ["予算", data.budgetRange],
    ["希望公開日", data.desiredLaunch],
    ["優先事項", data.priority],
    ["提供素材", data.materialsProvided.join("、")],
    ["ライティング担当", data.writingBy],
    ["運用体制", data.operationPlan],
    ["保守契約", data.maintenanceRequired ? "希望あり" : "希望なし"],
    ["サーバー種別", data.serverType],
    ["サーバー名・プラン", data.serverName],
    ["サーバーログイン情報", data.serverLoginInfo],
    ["ドメイン名", data.domainName],
    ["ドメイン管理会社", data.domainRegistrar],
    ["ドメイン有効期限", data.domainExpiry],
    ["SSL証明書", data.sslType],
    ["メールサーバー", data.mailServer],
    ["DNS管理", data.dnsManagement],
    ["備考", data.notes],
  ];

  const escCsv = (v: string) => {
    const s = v.replace(/\n/g, " ");
    if (s.includes(",") || s.includes('"')) return `"${s.replace(/"/g, '""')}"`;
    return s;
  };

  const bom = "\uFEFF";
  return (
    bom +
    "項目,内容\n" +
    rows.map(([k, v]) => `${escCsv(k)},${escCsv(v)}`).join("\n")
  );
}

export function generateHearingTsv(data: HearingSheet): string {
  const rows: [string, string][] = [
    ["会社名・団体名", data.clientName],
    ["業種", data.clientIndustry],
    ["現在のサイトURL", data.clientUrl],
    ["担当者名", data.contactPerson],
    ["メールアドレス", data.contactEmail],
    ["電話番号", data.contactPhone],
    ["現状の課題・背景", data.currentSituation],
    ["競合サイト", data.competitors],
    ["既存資料", data.existingMaterials],
    ["アクセス状況", data.accessAnalysis],
    ["強み", data.strengths],
    ["弱み", data.weaknesses],
    ["機会", data.opportunities],
    ["脅威", data.threats],
    ["ターゲットユーザー", data.targetUsers],
    ["ペルソナ年齢層", data.personaAge],
    ["ペルソナ性別", data.personaGender],
    ["ペルソナ職業", data.personaOccupation],
    ["ペルソナのニーズ", data.personaNeeds],
    ["カスタマージャーニー", data.customerJourney],
    ["ブランドメッセージ", data.brandMessage],
    ["KGI", data.kgi],
    ["KPI", data.kpi],
    ["収益化方針", data.monetization],
    ["プロジェクトの目的", data.projectGoal],
    ["サイト種別", data.siteType],
    ["必要なページ", data.requiredPages],
    ["必要な機能", data.features.join("、")],
    ["CMS", data.cmsType],
    ["デザインの方向性", data.designPreference],
    ["参考サイトURL", data.referenceUrls],
    ["レスポンシブ対応", data.responsiveRequired ? "必要" : "不要"],
    ["SEO対策", data.seoRequired ? "必要" : "不要"],
    ["アクセス解析", data.analyticsRequired ? "必要" : "不要"],
    ["SNS連携", data.snsIntegration.join("、")],
    ["予算", data.budgetRange],
    ["希望公開日", data.desiredLaunch],
    ["優先事項", data.priority],
    ["提供素材", data.materialsProvided.join("、")],
    ["ライティング担当", data.writingBy],
    ["運用体制", data.operationPlan],
    ["保守契約", data.maintenanceRequired ? "希望あり" : "希望なし"],
    ["サーバー種別", data.serverType],
    ["サーバー名・プラン", data.serverName],
    ["サーバーログイン情報", data.serverLoginInfo],
    ["ドメイン名", data.domainName],
    ["ドメイン管理会社", data.domainRegistrar],
    ["ドメイン有効期限", data.domainExpiry],
    ["SSL証明書", data.sslType],
    ["メールサーバー", data.mailServer],
    ["DNS管理", data.dnsManagement],
    ["備考", data.notes],
  ];

  const bom = "\uFEFF";
  return (
    bom +
    "項目\t内容\n" +
    rows.map(([k, v]) => `${k}\t${v.replace(/[\t\n]/g, " ")}`).join("\n")
  );
}
