import { describe, it, expect } from "vitest";
import {
  generateHearingHtml,
  generateHearingCsv,
  generateHearingTsv,
} from "@/lib/hearing/export";
import { createSampleHearing, createEmptyHearingForTest } from "./helpers";

describe("generateHearingHtml", () => {
  it("完全なHTMLドキュメントを返す", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("<!DOCTYPE html>");
    expect(html).toContain("<html lang=\"ja\">");
    expect(html).toContain("</html>");
  });

  it("クライアント名がタイトルに含まれる", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("ヒアリングシート - 株式会社テスト");
  });

  it("各セクションの内容が含まれる", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("クライアント基本情報");
    expect(html).toContain("現状分析");
    expect(html).toContain("SWOT分析");
    expect(html).toContain("ターゲット・ペルソナ");
    expect(html).toContain("戦略・ブランディング");
    expect(html).toContain("要件定義");
    expect(html).toContain("デザイン");
    expect(html).toContain("予算・スケジュール");
    expect(html).toContain("素材・運用");
    expect(html).toContain("サーバー・ドメイン");
  });

  it("features配列がカンマ区切りで表示される", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("お問い合わせフォーム、ブログ / お知らせ、FAQ / よくある質問");
  });

  it("boolean項目が適切にラベル変換される", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("必要"); // responsiveRequired: true
    expect(html).toContain("希望あり"); // maintenanceRequired: true
  });

  it("不要なフィールドはfalse時に適切に表示", () => {
    const data = createSampleHearing({
      responsiveRequired: false,
      maintenanceRequired: false,
    });
    const html = generateHearingHtml(data);
    expect(html).toContain("不要");
    expect(html).toContain("希望なし");
  });

  it("HTMLエスケープが正しく動作する", () => {
    const data = createSampleHearing({
      clientName: '<script>alert("xss")</script>',
    });
    const html = generateHearingHtml(data);
    expect(html).not.toContain("<script>");
    expect(html).toContain("&lt;script&gt;");
  });

  it("空データの場合はセクションが省略される", () => {
    const html = generateHearingHtml(createEmptyHearingForTest());
    // 全フィールドが空なので、テーブル行が生成されない
    expect(html).toContain("ヒアリングシート");
    expect(html).toContain("未設定");
  });

  it("備考がある場合は備考セクションが表示される", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("備考");
    expect(html).toContain("6月の株主総会前に公開したい");
  });

  it("備考がない場合は備考セクションが省略される", () => {
    const data = createSampleHearing({ notes: "" });
    const html = generateHearingHtml(data);
    // 備考セクション自体が出力されないことを確認
    const notesSectionCount = (html.match(/メモ/g) || []).length;
    expect(notesSectionCount).toBe(0);
  });

  it("ステータスが正しく表示される", () => {
    const completed = generateHearingHtml(
      createSampleHearing({ status: "completed" })
    );
    expect(completed).toContain("完了");

    const draft = generateHearingHtml(
      createSampleHearing({ status: "draft" })
    );
    expect(draft).toContain("下書き");
  });

  it("フッターが含まれる", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("Generated by WebCraft");
  });

  it("印刷用CSSが含まれる", () => {
    const html = generateHearingHtml(createSampleHearing());
    expect(html).toContain("@media print");
  });
});

describe("generateHearingCsv", () => {
  it("BOM付きで始まる", () => {
    const csv = generateHearingCsv(createSampleHearing());
    expect(csv.startsWith("\uFEFF")).toBe(true);
  });

  it("ヘッダー行がある", () => {
    const csv = generateHearingCsv(createSampleHearing());
    expect(csv).toContain("項目,内容");
  });

  it("全フィールドが行として出力される", () => {
    const csv = generateHearingCsv(createSampleHearing());
    const lines = csv.split("\n");
    // BOM + ヘッダー + データ行
    expect(lines.length).toBeGreaterThan(30);
  });

  it("クライアント名が含まれる", () => {
    const csv = generateHearingCsv(createSampleHearing());
    expect(csv).toContain("株式会社テスト");
  });

  it("カンマを含む値がダブルクォートで囲まれる", () => {
    const data = createSampleHearing({ clientName: "テスト,カンパニー" });
    const csv = generateHearingCsv(data);
    expect(csv).toContain('"テスト,カンパニー"');
  });

  it("ダブルクォートを含む値がエスケープされる", () => {
    const data = createSampleHearing({ clientName: 'テスト"企業"' });
    const csv = generateHearingCsv(data);
    expect(csv).toContain('"テスト""企業"""');
  });

  it("改行がスペースに変換される", () => {
    const data = createSampleHearing({
      currentSituation: "課題1\n課題2\n課題3",
    });
    const csv = generateHearingCsv(data);
    expect(csv).toContain("課題1 課題2 課題3");
  });

  it("boolean項目がラベル変換されている", () => {
    const csv = generateHearingCsv(createSampleHearing());
    expect(csv).toContain("必要"); // responsive, seo
    expect(csv).toContain("希望あり"); // maintenance
  });

  it("features配列がカンマ区切りで出力される", () => {
    const csv = generateHearingCsv(createSampleHearing());
    expect(csv).toContain("お問い合わせフォーム、ブログ / お知らせ、FAQ / よくある質問");
  });
});

describe("generateHearingTsv", () => {
  it("BOM付きで始まる", () => {
    const tsv = generateHearingTsv(createSampleHearing());
    expect(tsv.startsWith("\uFEFF")).toBe(true);
  });

  it("ヘッダー行がタブ区切り", () => {
    const tsv = generateHearingTsv(createSampleHearing());
    expect(tsv).toContain("項目\t内容");
  });

  it("データがタブ区切りで出力される", () => {
    const tsv = generateHearingTsv(createSampleHearing());
    expect(tsv).toContain("会社名・団体名\t株式会社テスト");
  });

  it("タブ文字がスペースに変換される", () => {
    const data = createSampleHearing({
      currentSituation: "課題1\t課題2",
    });
    const tsv = generateHearingTsv(data);
    expect(tsv).toContain("課題1 課題2");
  });

  it("改行がスペースに変換される", () => {
    const data = createSampleHearing({
      currentSituation: "行1\n行2",
    });
    const tsv = generateHearingTsv(data);
    expect(tsv).toContain("行1 行2");
  });

  it("全フィールドが行として出力される", () => {
    const tsv = generateHearingTsv(createSampleHearing());
    const lines = tsv.split("\n");
    expect(lines.length).toBeGreaterThan(30);
  });
});
