import type { HearingSheet } from "@/types/hearing";

// テスト用のサンプルヒアリングデータ
export function createSampleHearing(
  overrides?: Partial<HearingSheet>
): HearingSheet {
  return {
    clientName: "株式会社テスト",
    clientIndustry: "IT・Web",
    clientUrl: "https://example.com",
    contactPerson: "山田太郎",
    contactEmail: "yamada@example.com",
    contactPhone: "03-1234-5678",
    currentSituation: "現在のサイトが古く、スマートフォン対応ができていない",
    competitors: "https://competitor1.com, https://competitor2.com",
    existingMaterials: "ロゴデータ、会社パンフレット",
    accessAnalysis: "月間PV: 5,000 / UU: 2,000",
    strengths: "20年の実績、技術力",
    weaknesses: "Web集客が弱い",
    opportunities: "DX需要の高まり",
    threats: "競合のWeb強化",
    targetUsers: "中小企業の経営者・IT担当者",
    personaAge: "40代",
    personaGender: "男性",
    personaOccupation: "経営者",
    personaNeeds: "業務効率化、コスト削減",
    customerJourney: "Google検索 → サイト訪問 → 資料請求 → 商談",
    brandMessage: "信頼と技術で未来をつくる",
    kgi: "年間売上20%アップ",
    kpi: "月間問い合わせ数30件",
    monetization: "サービス受注",
    projectGoal: "リニューアルによる集客強化と問い合わせ数増加",
    siteType: "コーポレートサイト",
    requiredPages: "トップ、会社概要、事業内容、実績、採用、お問い合わせ",
    features: ["お問い合わせフォーム", "ブログ / お知らせ", "FAQ / よくある質問"],
    cmsType: "WordPress",
    designPreference: "シンプルでモダン、信頼感のあるデザイン",
    referenceUrls: "https://reference1.com",
    responsiveRequired: true,
    seoRequired: true,
    analyticsRequired: true,
    snsIntegration: ["X (Twitter)", "Instagram"],
    budgetRange: "100〜200万円",
    desiredLaunch: "2026-06-01",
    priority: "品質重視",
    materialsProvided: ["ロゴデータ", "写真素材"],
    writingBy: "制作会社に依頼",
    operationPlan: "社内で更新運用",
    maintenanceRequired: true,
    serverType: "レンタルサーバー",
    serverName: "さくらインターネット スタンダード",
    serverLoginInfo: "",
    domainName: "example.com",
    domainRegistrar: "お名前.com",
    domainExpiry: "2027-03-01",
    sslType: "無料SSL（Let's Encrypt）",
    mailServer: "さくらメール",
    dnsManagement: "お名前.com",
    createdAt: "2026-03-09",
    updatedAt: "2026-03-09",
    status: "completed",
    notes: "6月の株主総会前に公開したい",
    ...overrides,
  };
}

// 空のヒアリングデータ
export function createEmptyHearingForTest(): HearingSheet {
  return {
    clientName: "",
    clientIndustry: "",
    clientUrl: "",
    contactPerson: "",
    contactEmail: "",
    contactPhone: "",
    currentSituation: "",
    competitors: "",
    existingMaterials: "",
    accessAnalysis: "",
    strengths: "",
    weaknesses: "",
    opportunities: "",
    threats: "",
    targetUsers: "",
    personaAge: "",
    personaGender: "",
    personaOccupation: "",
    personaNeeds: "",
    customerJourney: "",
    brandMessage: "",
    kgi: "",
    kpi: "",
    monetization: "",
    projectGoal: "",
    siteType: "",
    requiredPages: "",
    features: [],
    cmsType: "",
    designPreference: "",
    referenceUrls: "",
    responsiveRequired: true,
    seoRequired: true,
    analyticsRequired: true,
    snsIntegration: [],
    budgetRange: "",
    desiredLaunch: "",
    priority: "",
    materialsProvided: [],
    writingBy: "",
    operationPlan: "",
    maintenanceRequired: false,
    serverType: "",
    serverName: "",
    serverLoginInfo: "",
    domainName: "",
    domainRegistrar: "",
    domainExpiry: "",
    sslType: "",
    mailServer: "",
    dnsManagement: "",
    createdAt: "2026-03-09",
    updatedAt: "2026-03-09",
    status: "draft",
    notes: "",
  };
}
