import type { SitemapNode, SitemapProject } from "@/types/sitemap-generator";

function renderTreeHtml(nodes: SitemapNode[], color: string): string {
  if (nodes.length === 0) return "";
  const items = nodes
    .map(
      (n) => `
    <li>
      <div class="node" onclick="this.parentElement.classList.toggle('collapsed')">
        <span class="icon">${n.icon}</span>
        <div class="node-info">
          <span class="name">${esc(n.name)}</span>
          ${n.slug ? `<span class="slug">${esc(n.slug)}</span>` : ""}
          ${n.description ? `<p class="desc">${esc(n.description)}</p>` : ""}
        </div>
        ${n.children.length > 0 ? '<span class="toggle">▼</span>' : ""}
      </div>
      ${n.children.length > 0 ? renderTreeHtml(n.children, color) : ""}
    </li>`
    )
    .join("\n");
  return `<ul>${items}</ul>`;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function generateExportHtml(project: SitemapProject): string {
  const tree = renderTreeHtml(project.pages, project.themeColor);
  const color = project.themeColor;

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(project.siteName || "サイトマップ")}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; background: #f8fafc; color: #1e293b; padding: 40px 20px; }
  .header { max-width: 900px; margin: 0 auto 32px; }
  .header h1 { font-size: 24px; color: ${color}; margin-bottom: 8px; }
  .meta { display: flex; gap: 24px; flex-wrap: wrap; font-size: 13px; color: #64748b; }
  .meta span { display: flex; align-items: center; gap: 4px; }
  ${project.memo ? `.memo { max-width: 900px; margin: 0 auto 24px; padding: 12px 16px; background: #f1f5f9; border-radius: 8px; font-size: 13px; color: #475569; }` : ""}
  .tree { max-width: 900px; margin: 0 auto; }
  ul { list-style: none; padding-left: 24px; }
  .tree > ul { padding-left: 0; }
  li { position: relative; }
  li::before { content: ""; position: absolute; left: -16px; top: 0; bottom: 0; width: 1px; background: #e2e8f0; }
  li:last-child::before { bottom: 50%; }
  li::after { content: ""; position: absolute; left: -16px; top: 20px; width: 16px; height: 1px; background: #e2e8f0; }
  .tree > ul > li::before, .tree > ul > li::after { display: none; }
  .node { display: flex; align-items: flex-start; gap: 10px; padding: 8px 12px; margin: 4px 0; border-radius: 8px; border: 1px solid #e2e8f0; background: #fff; cursor: pointer; transition: border-color 0.15s; }
  .node:hover { border-color: ${color}; }
  .icon { font-size: 18px; flex-shrink: 0; margin-top: 2px; }
  .node-info { flex: 1; min-width: 0; }
  .name { font-weight: 600; font-size: 14px; }
  .slug { display: inline-block; margin-left: 8px; font-size: 12px; color: #94a3b8; font-family: monospace; }
  .desc { font-size: 12px; color: #64748b; margin-top: 2px; }
  .toggle { font-size: 10px; color: #94a3b8; margin-top: 6px; transition: transform 0.2s; }
  li.collapsed > .node .toggle { transform: rotate(-90deg); }
  li.collapsed > ul { display: none; }
  .footer { max-width: 900px; margin: 40px auto 0; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print {
    body { padding: 20px; background: #fff; }
    .node { break-inside: avoid; }
  }
</style>
</head>
<body>
<div class="header">
  <h1>${esc(project.siteName || "サイトマップ")}</h1>
  <div class="meta">
    ${project.clientName ? `<span>クライアント: ${esc(project.clientName)}</span>` : ""}
    ${project.companyName ? `<span>制作: ${esc(project.companyName)}</span>` : ""}
    <span>作成日: ${esc(project.createdAt)}</span>
  </div>
</div>
${project.memo ? `<div class="memo">${esc(project.memo)}</div>` : ""}
<div class="tree">${tree}</div>
<div class="footer">Generated by WebCraft</div>
</body>
</html>`;
}
